baseURL: "https://agajareiitr.github.io/"
title: Akash Gajare
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Akash Gajare"
    description: "Portfolio and Blog"
    keywords: [Blog, Portfolio, PaperMod]
    author: "Akash Gajare"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "images/favicon.ico"
        favicon16x16: "images/favicon-16x16.png"
        favicon32x32: "images/favicon-32x32.png"
        apple_touch_icon: "images/apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "アカシュ[ Akash ]"
        # icon: images/apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there , I am Akash Gajare"
        Content: >
                ⭐ I am a **Python Developer** and a **Data Analyst**. I have 2 Years of Experience in Python making Automation Scripts and Web Scrapping.
                
                - ⭐ I have been learning **Django, Flask, Rest Framework, JavaScript etc**.
                
                - ⭐ My further Learning Curve Includes **React-JS and React-Native** for building Cross-platform apps.

                - ⭐ Topics like **Blockchain** and **cloud computing** etc exites me.
                
                - ⭐ kepping aside Academics I also Love to Watch **Anime** in my free time and has a keen interest in
                **Japan** and **Japanese Culture**.

    socialIcons:
        - name: linkedin	
          url: "https://www.linkedin.com/in/agajareiitr/"
        - name: github
          url: "https://github.com/agajareiitr"
        - name: email
          url: "mailto:agajare@ch.iitr.ac.in"
        - name: instagram
          url: "https://www.instagram.com/agajareiitr/"
        - name: anilist
          url: "https://anilist.co/user/deva0811/"

    analytics:
        google:
            SiteVerificationTag: "xShfHgWIY5XEqN7SELwVlnkroW9nYHOgbVONqxAmcNY"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/agajareiitr/agajareiitrblog/tree/main/content/"
        Text: "Suggest Changes \U0001F448" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Resume
          name: Resume
          url: /Resume/
          weight: 10
        - identifier: aboutme
          name: About Me
          url: /aboutme/
          weight: 30
        - identifier: Projects
          name: Projects
          url: /projects/
          weight: 20
        - identifier: search
          name: Search
          url: /Search/
          weight: 40

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

# for search functionality
outputs:
    home:
        - HTML
        - RSS
        - JSON